package com.digitinary.training.task.entity;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

/**
 * 
 * Jun 14, 2021
 * @author Salah Abu Msameh
 */
//TODO: TABLE NAME >>>>> STUDENTS
public class Student {
	
	private Long studentId;
	private String name;
	private Gender gender;
	private String major;
	private LocalDate joinDate;
	
	//
	private Set<Course> courses = new HashSet<Course>();
	
	//TODO: id column
	//TODO: auto generated by sequence
	public Long getStudentId() {
		return studentId;
	}
	
	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Gender getGender() {
		return gender;
	}
	
	//TODO: there is an annotation (google it)
	public void setGender(Gender gender) {
		this.gender = gender;
	}
	
	public String getMajor() {
		return major;
	}
	
	public void setMajor(String major) {
		this.major = major;
	}
	
	public LocalDate getJoinDate() {
		return joinDate;
	}
	
	public void setJoinDate(LocalDate joinDate) {
		this.joinDate = joinDate;
	}

	public Set<Course> getCourses() {
		return courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}
}
